version: '3.8'

services:

  bradford_dash:
    build: .
    image: bradford_dash
    container_name: bradford_dash
    ports:
      - 8052:8052

    stdin_open: true # docker run -i
    tty: true        # docker run -t

    volumes:
      - .:/src

