[runner]

# Run the Python Garbage Collector after each script execution. This can help avoid excess memory use in Streamlit apps, but could introduce delay in rerunning the app script for high-memory-use applications.
# Default: true
postScriptGC = false

[server]
port=8052 # change port number. By default streamlit uses 8501 port
address = "0.0.0.0"
enableCORS = false
enableWebsocketCompression = false
enableXsrfProtection = false
headless=true # This will eliminate automatically open browser
enableStaticServing = false

[global]
developmentMode = false

[browser]
gatherUsageStats = true